[package]
name = "goober-sync-hub"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full", "macros"] }
tokio-tungstenite = "0.15"
futures = "0.3"
log = "0.4"
uuid = "1.17.0"
env_logger = "0.11.8"
